apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""                                                          # Quando não informa a storage Class, é necessário utilizar o volumeName
  volumeName: example-pv                                                        # volumeName referenciando o example-pv